version: '3.6'

services:
  pulsar:
    image: "apachepulsar/pulsar:2.7.0"
    # container_name: pulsar
    volumes:
      - ./data/pulsar-data:/pulsar/data
    ports:
      - "6650:6650"
      - "8080:8080"
    command: "bin/pulsar standalone"
  postgres-db:
    image: "postgres:11"
    environment:
      - "POSTGRES_PASSWORD=example"
      - "POSTGRES_USER=default"
      - "POSTGRES_DB=default"
    ports:
      - "5480:5432"
